function(faeditor_product_metadata product out_target out_name out_bundle_id out_version out_bundle_version out_qml_uri out_qml_main)
    if(product STREQUAL "FA")
        set(values "FAEditor;FA Editor;com.righthere.faeditor;1.1;4;FAEditor;Main")
    elseif(product STREQUAL "FANTOM")
        set(values "FantomEditor;Fantom Editor;com.righthere.fantomeditor;0.1;1;FantomEditor;FantomMain")
    else()
        message(FATAL_ERROR "Invalid FAEDITOR_PRODUCT='${product}'. Expected FA or FANTOM.")
    endif()

    list(GET values 0 target)
    list(GET values 1 name)
    list(GET values 2 bundle_id)
    list(GET values 3 version)
    list(GET values 4 bundle_version)
    list(GET values 5 qml_uri)
    list(GET values 6 qml_main)
    set(${out_target} "${target}" PARENT_SCOPE)
    set(${out_name} "${name}" PARENT_SCOPE)
    set(${out_bundle_id} "${bundle_id}" PARENT_SCOPE)
    set(${out_version} "${version}" PARENT_SCOPE)
    set(${out_bundle_version} "${bundle_version}" PARENT_SCOPE)
    set(${out_qml_uri} "${qml_uri}" PARENT_SCOPE)
    set(${out_qml_main} "${qml_main}" PARENT_SCOPE)
endfunction()
